# Generated by Django 5.2.7 on 2025-10-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={},
        ),
        migrations.RenameField(
            model_name='instruction',
            old_name='title',
            new_name='ins_title',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='content',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='page',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='quiz.instruction')),
            ],
        ),
    ]
