# Generated by Django 5.2.7 on 2025-10-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_instruction_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='title',
            new_name='ins_title',
        ),
        migrations.RenameField(
            model_name='instruction',
            old_name='ins_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='instruction',
            name='page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
