# Generated by Django 5.2.7 on 2025-10-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_title_content_ins_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='button',
            new_name='button_bangla',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='page',
            new_name='button_english',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='subtitle',
            new_name='subtitle_bangla',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='title',
            new_name='title_english',
        ),
        migrations.AddField(
            model_name='banner',
            name='page_bangla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='page_english',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_bangla',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
