# Generated by Django 5.2.7 on 2025-10-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='page_bangla',
            new_name='page',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='page_english',
        ),
    ]
