# Generated by Django 5.2.7 on 2025-10-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_page_bangla_banner_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='ins_title',
            new_name='ins_title_en',
        ),
        migrations.RenameField(
            model_name='instruction',
            old_name='page',
            new_name='page_bn',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='title',
        ),
        migrations.AddField(
            model_name='content',
            name='content_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='ins_title_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='page_en',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='title_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/uploads/'),
        ),
    ]
