# Generated by Django 5.2.7 on 2025-10-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_content_content_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='page_bn',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
