# Generated by Django 5.2.7 on 2025-10-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_content_content_en_alter_instruction_page_bn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='page_bn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
