# Generated by Django 5.2.7 on 2025-10-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_instruction_page_bn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='page_bn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
